name: Deployment
run-name: ${{github.actor}} trigger an event.

on: [push]
jobs:
  print_hello:
    runs-on: ubuntu_latest
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v3
      - run: echo "Hello, Detector"