name: Deployment
run-name: ${{ github.actor }} triggered an event.
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello, Detector"