name: Deployment
run-name: ${{github.actor}} trigger an event.

on: [push]
jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v3
      - run: echo "Hello, Detector"