name: Deployment
run-name: ${{ github.actor }} triggered an event.
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main 
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello, Detector"
      - name: First Interaction
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          issue-message: '${{github.actor}}\'s first issue.'
          pr-message: ${{github.actor}}\'s first PR.